### 注册服务
POST localhost:8787/register?service=app1_public_dev_cc.rpc.demo.api.UserService
Content-Type: application/json

{
  "scheme": "http",
  "host": "127.0.0.1",
  "port": 8081,
  "context": ""
}

### 取消注册服务
POST localhost:8787/unregister?service=app1_public_dev_cc.rpc.demo.api.UserService
Content-Type: application/json

{
  "scheme": "http",
  "host": "127.0.0.1",
  "port": 8081
}


### 查询服务
GET http://localhost:8787/fetchAll?service=app1_public_dev_cc.rpc.demo.api.UserService

### 查看版本
GET http://localhost:8787/version?service=app1_public_dev_cc.rpc.demo.api.UserService

### 查看时间戳
GET http://localhost:8787/timestamps

### 获取集群信息
GET http://localhost:8787/cluster

### 查看快照
GET http://localhost:8787/snapshot

### 订阅服务变更
GET http://localhost:8787/subscribe?service=app1_public_dev_cc.rpc.demo.api.UserService




